name: ssl_wafermap
channels:
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - pytorch
    - torchvision
    - torchaudio
    - pandas
    - umap-learn
    - scikit-learn
    - hdbscan
    - seaborn
    - plotly
    - bokeh
    - tqdm
    - black
    - dill
    - wandb
    - ca-certificates
    - certifi
    - openssl
    - pyscaffoldext-dsproject
    - pre-commit
    - albumentations
    - ipykernel
    - ipywidgets
    - nbformat
    - zstandard
    - kaggle
    - pipreqs
    - pip:
          - -r requirements.txt
          - -e .
